### ISSUE TITLE
Remove 'social media' preview from pipeline health page

### ISSUE THREAD

**Issue by jfy133** [nf-core/nf-co.re#785] opened 2021-06-03 10:03 UTC
As the custom social media previews have been superseeded by the pretty auto Github one. Therefore currently all pipelines 'fail' on this.

**Comment by ewels** [comment] 2021-06-03 10:08
Duplicate of https://github.com/nf-core/nf-co.re/issues/750

**Closed by ewels** 2021-06-03 10:08 UTC
Labels: bug
