### ISSUE TITLE
json schema escaped `\`

### ISSUE THREAD

**Issue by ggabernet** [nf-core/nf-co.re#499] opened 2020-09-10 20:40 UTC
When editing the parameter json schema with the web builder, the `/` characters are escaped to `&#x2F;`. 

For example, the igenomes_base parameter default is set to `s3://ngi-igenomes`

<img width="1146" alt="Screenshot 2020-09-10 at 19 40 58" src="https://user-images.githubusercontent.com/3973503/92802030-7160fb00-f3b6-11ea-8988-bb3c3c4046f3.png">

But when opening the schema with the web builder and save it again, it is stored in the json file as: `s3:&#x2F;&#x2F;ngi-igenomes`

<img width="521" alt="Screenshot 2020-09-10 at 19 41 39" src="https://user-images.githubusercontent.com/3973503/92802163-8e95c980-f3b6-11ea-8b86-00ebd4d4846f.png">

And also displayed as: `s3:\/\/ngi-igenomes` in the json web viewer:

<img width="613" alt="Screenshot 2020-09-10 at 20 00 05" src="https://user-images.githubusercontent.com/3973503/92802270-a8cfa780-f3b6-11ea-8be9-4c584b0d74a3.png">

**Comment by mashehu** [comment] 2020-09-21 11:02
Looked quickly into this and I think it works as intended in chrome, but not on firefox 😞 

@ggabernet: which browser were you using?

**Comment by ggabernet** [comment] 2020-09-21 12:37
I'm using chrome usually. I can test again sometime this evening but 99% sure I did that with chrome.

**Comment by ggabernet** [comment] 2020-09-21 13:01
I've just tested it again and it happened again with chrome: 
`nf-core version 1.10.2` 
`google chrome version 85.0.4183.83` for MacOS

**Comment by ggabernet** [comment] 2020-09-21 13:02
@Leon-Bichmann had the same issue. Which browser are you using? And version?

**Comment by mashehu** [comment] 2020-09-21 13:18
okay, if you are also using chrome, my theory is not valid and I have to look deeper into it (my version is 85.0.4183.102, but that shouldn't make a big difference).  

I could now partially reproduce the bug. For some reason it works for me in the case of `igenomes_base`, which is why I thought it works in chrome. But I now found several other instances of printed html character codes in the json file.

**Comment by mashehu** [comment] 2020-09-21 14:49
Made a hot-fix (#503) for the issue, but it is by far not an optimal solution.

The basic problem is: We added a sanitize function for strings, to escape special characters in #492 to fix #489. Unfortunately, the html entities are directly written into the schema object and never decoded in a later step (I assumed `JSON.parse()` would do this).

**Comment by ggabernet** [comment] 2020-09-21 16:19
awesome, thanks!

**Comment by mashehu** [comment] 2020-10-13 13:12
Fixed with #503

**Closed by mashehu** 2020-10-13 13:12 UTC
Labels: bug, enhancement
