### ISSUE TITLE
Broken Links to design files

### ISSUE THREAD

**Issue by alaincoletta** [nf-core/nf-co.re#512] opened 2020-09-29 13:39 UTC
https://nf-co.re/atacseq/1.2.1/assets/design_pe.csv
and 
https://nf-co.re/atacseq/1.2.1/assets/design_se.csv
return a 404. They referenced at the end of this section: 
https://nf-co.re/atacseq/1.2.1/usage#--input

https://nf-co.re/chipseq/1.2.1/assets/design_pe.csv
and
https://nf-co.re/chipseq/1.2.1/assets/design_se.csv
return a 404. They referenced at the end of this section: 

referenced at the end of this section: 
https://nf-co.re/chipseq/1.2.1/usage#--input

**Comment by apeltzer** [comment] 2020-09-30 11:20
Probably it would be safest to use Fully Qualified URLs here @drpatelh - that should resolve these issues?

**Comment by drpatelh** [comment] 2020-09-30 11:32
Sorry, I missed this. Yup I suspect it's because of the recent changes to the website. Which branch would we point to in the full URLs? With relative URLs that doesn't matter. Or am I missing something? Ping @ewels @mashehu

**Comment by apeltzer** [comment] 2020-09-30 13:13
Relative has the benefit that it stays up2date no matter when there is a new release. If we remove links like this in an upcoming release (and thus subsequently from `master`) a previous link to master will be gone too - so maybe we should link to a specific tag instead? Not sure how to achieve this though...

**Comment by mashehu** [comment] 2020-09-30 13:41
We have a full link to the master branch for the igenome confs, as resolved here: https://github.com/nf-core/tools/pull/691/files. Since the docs on the website are available for different version, it might actually be good to reparse these kind of links and replace `blob/master` with `blob/$version`.

**Comment by drpatelh** [comment] 2020-09-30 14:06
Yes, I think we should somehow point/redirect to the version of a file stored under a particular tag. Maybe replace both `blob/master` and `blob/dev` with `blob/$version` for any release tagged docs on the website? There will be instances where certain files are added to `dev` first and so may not be on `master` until release - at which point the pipeline author may forget to update `dev` -> `master` in the links.

I guess the problem with relative URLs is that the file can be deleted in a new release but the link from older releases will still point to `master` where it no longer exists.

**Comment by drpatelh** [comment] 2020-09-30 14:14
Also, is this something we can lint for? I think it is something that can be easily missed and will only be updated on new release 🤔

**Comment by mashehu** [comment] 2020-09-30 14:22
you mean linting for relative urls or for occurences of `/blob/dev`?

**Comment by ewels** [comment] 2020-10-10 17:14
I think that it would be better to just make the relative URLs work. I'm going to have a quick play.

**Comment by ewels** [comment] 2020-10-10 17:30
Ok, try #517 - should basically make these links work properly again.

**Comment by drpatelh** [comment] 2020-10-12 12:05
I can confirm the changes introduced in #517 have now fixed this issue 🚀

**Closed by drpatelh** 2020-10-12 12:05 UTC
Labels: bug, documentation
