### ISSUE TITLE
Reference Genomes link on website broken

### ISSUE THREAD

**Issue by saharai** [nf-core/nf-co.re#170] opened 2019-08-28 20:29 UTC
Hello - wanted to click on https://nf-co.re/usage/usage/reference_genomes to learn more but the link is broken.

**Comment by drpatelh** [comment] 2019-08-28 20:37
Hi @saharai ! Thanks for reporting this. It seems a couple of links are broken on this page:
https://github.com/nf-core/nf-co.re/blob/master/markdown/usage/installation.md

And on this page:
https://github.com/nf-core/nf-co.re/blob/9e1bd2b4c2b94046ddd782289832fc1e7f173d91/markdown/usage/installation.md

The website has been quite extensively restructured recently. Sorry, will need to double check them. However, the page is there if you want to have a look:
https://github.com/nf-core/nf-co.re/blob/master/markdown/usage/reference_genomes.md

**Comment by ewels** [comment] 2019-08-28 21:50
Thanks for the spot @saharai! Should be fixed in #171 - was caused by a restructuring as @drpatelh says.

> And on this page:

Both of these links are for the same installation page? Did you mean to link to a different markdown file?

**Comment by drpatelh** [comment] 2019-08-28 21:54
Yeah, sorry was replying on my phone :sweat_smile: 
https://github.com/nf-core/nf-co.re/blob/8b2481fd5d1a6e5f17ef68fe9c1d59b40002b6ba/markdown/usage/local_installation.md

**Comment by drpatelh** [comment] 2019-08-28 22:02
Actually, the `Reference Genomes` link may be ok on the page above. Its not working if you click on it via markdown but it should work on the website? i.e with the `.md` extension.

**Comment by ewels** [comment] 2019-09-03 09:20
I got the website to automatically remove the `.md` endings in links, so they should have them. That way they will work on both the website and on Github / rendered markdown.

**Closed** 2019-09-03 15:29 UTC
